export const site = {
  name: 'Mayur Dholera',
  tagline: 'Premium Plots near Dholera Smart City',
  phone: '9899974590',
  phoneAlt: '7042367340',
  phoneDisplay: '+91 98999 74590',
  email: 'info@mayurdholera.com',
  address: 'Site: Near Dholera International Airport, Dholera SIR, Gujarat',
  whatsappMessage:
    'Hi! I am interested in Mayur Dholera projects. Please share current prices and plot availability.',
};

export const stats = [
  { value: '₹91,000 Cr', label: 'Tata Semiconductor Fab in Dholera' },
  { value: '15+', label: 'Projects Delivered in Dholera' },
  { value: '920 km²', label: "India's Largest Planned Smart City" },
  { value: '2026', label: 'International Airport Operational' },
];

export const whyDholera = [
  {
    icon: 'Landmark',
    title: 'Government-Backed SIR',
    text: "Dholera is a Gujarat Government notified Special Investment Region under the Delhi–Mumbai Industrial Corridor (DMIC) — India's first and largest greenfield smart city, with plug-and-play trunk infrastructure already built.",
  },
  {
    icon: 'Cpu',
    title: '₹91,000 Cr Semiconductor Hub',
    text: "Tata Electronics' mega semiconductor fabrication plant — producing India's first homegrown chips — anchors Dholera's industrial ecosystem, drawing suppliers, engineers and housing demand.",
  },
  {
    icon: 'Plane',
    title: 'International Airport',
    text: 'Dholera International Airport (Navagam) is in advanced construction, designed for both cargo and passenger operations — a direct catalyst for land appreciation around the SIR.',
  },
  {
    icon: 'Route',
    title: 'Expressway Connectivity',
    text: 'The 109 km, 4-lane Ahmedabad–Dholera Expressway cuts travel time to under an hour, with high-speed rail and metro links planned along the corridor.',
  },
  {
    icon: 'TrendingUp',
    title: 'Early-Growth Pricing',
    text: 'Plot rates in Dholera are still in the early phase — roughly ₹6,000–₹10,000 per sq yd against mature Ahmedabad markets, giving investors a rare ground-floor entry.',
  },
  {
    icon: 'ShieldCheck',
    title: 'Clear-Title, Legal Plots',
    text: 'Every plot is NA (Non-Agricultural), NOC-approved, title clear and plan passed — sold with registered sale deed for a fully transparent purchase.',
  },
];

export const projects = [
  {
    name: 'Mayur NOVA',
    slug: 'mayur-nova',
    type: 'Residential Plots',
    category: 'Ongoing',
    location: 'Ratanpur, Dholera Smart City',
    price: 'On Request',
    priceUnit: 'New Launch',
    size: '90 plots · 132–655 sq yd',
    status: 'New Launch',
    image: 'https://mirrikh.com/wp-content/uploads/2026/07/Mayur-NOVA-cover-banner-2.jpg',
    highlights: [
      'NA, NOC, Title Clear & Unit Plan Pass',
      'Gated Community with Club House',
      '10 km from Dholera International Airport',
      '9 km from Ahmedabad–Dholera Expressway',
    ],
    accent: '#f26522',
    desc: 'Mayur NOVA is a premium residential plotting project situated in Ratanpur. Featuring 90 exclusive plots ranging from 132 to 655 sq yd, the project comes with complete NA, NOC, and title clearance. Enjoy world-class amenities including a modern clubhouse within a secure gated community.',
  },
  {
    name: 'Mayur Aerocity 2',
    slug: 'mayur-aerocity-2',
    type: 'Residential Plots',
    category: 'Ongoing',
    location: 'Near Dholera International Airport',
    price: 'On Request',
    priceUnit: 'Pre-Launch Pricing',
    size: 'Multiple plot sizes',
    status: 'Pre-Launch',
    image: 'https://mirrikh.com/wp-content/uploads/2026/07/Mayur-Aerocity-ll-cover-bg3.jpg',
    highlights: [
      'Closest project to Dholera Airport',
      'High appreciation potential',
      'NA · NOC · Title Clear',
      'Registered sale deed guaranteed',
    ],
    accent: '#3b82f6',
    desc: 'Strategically located near the upcoming Dholera International Airport, Mayur Aerocity II is designed for investors seeking high appreciation. The project offers premium plotting options with guaranteed registered sale deeds and unmatched proximity to major transport hubs.',
  },
  {
    name: 'Estate 5',
    slug: 'estate-5',
    type: 'Residential Plots',
    category: 'Ongoing',
    location: 'Dholera Smart City (TP Area)',
    price: 'On Request',
    priceUnit: 'Ongoing',
    size: '20 bighas enclave',
    status: 'Ongoing',
    image: 'https://mirrikh.com/wp-content/uploads/2026/06/banner-Mayur-Park-3-1.jpg',
    highlights: [
      'Well-planned internal roads & lighting',
      'Green open areas',
      'Registered sale deed completed',
      'NA · NOC · Title Clear',
    ],
    accent: '#e8c774',
    desc: 'Estate 5 is an exclusive 20-bigha residential enclave situated right at the boundary of Dholera SIR. With meticulously planned internal roads, lush green open areas, and complete legal clearance, it represents a secure and profitable investment.',
  },
  {
    name: 'Emerald Heights',
    slug: 'emerald-heights',
    type: 'Residential Plots',
    category: 'Ongoing',
    location: 'Dholera Smart City',
    price: 'On Request',
    priceUnit: 'Ongoing',
    size: 'Multiple plot sizes',
    status: 'Ongoing',
    image: 'https://mirrikh.com/wp-content/uploads/2026/05/Mayur-Forest-Villa-Web-Banner-1.png',
    highlights: [
      'Forest-themed residential community',
      'Lush greenery & landscaped spaces',
      'Gated community with premium amenities',
      'NA · NOC · Title Clear',
    ],
    accent: '#22c55e',
    desc: 'Emerald Heights offers a unique forest-themed residential experience inside Dholera Smart City. Immerse yourself in lush greenery, beautifully landscaped spaces, and premium amenities in a fully secure, gated community.',
  },
  {
    name: 'Emerald Commercial Hub',
    slug: 'emerald-commercial-hub',
    type: 'Commercial Plots',
    category: 'Commercial',
    location: 'Dholera Commercial Zone',
    price: 'On Request',
    priceUnit: 'Pre-Launch',
    size: 'Large-format plots',
    status: 'Ongoing',
    image: 'https://mirrikh.com/wp-content/uploads/2026/04/Mayur-Greenz-Courtyard-Web-Banner.jpg',
    highlights: [
      'Premium commercial and retail spaces',
      'High footfall connectivity',
      'Near semiconductor & industrial belt',
      'Heavy-vehicle friendly access roads',
    ],
    accent: '#f59e0b',
    desc: 'Emerald Commercial Hub is positioned in the heart of Dholera\'s commercial zone. Designed to support retail, corporate offices, and logistics, it offers large-format plots with heavy-vehicle access, situated close to the Tata Semiconductor Fab.',
  },
  {
    name: 'Dholera Iconic RERA Approved Commercial Shops',
    slug: 'dholera-iconic-rera-approved-commercial-shops',
    type: 'Commercial Shops',
    category: 'Commercial',
    location: 'Dholera Smart City',
    price: 'On Request',
    priceUnit: 'Ready to Move',
    size: 'Multiple configurations',
    status: 'Ready',
    image: 'https://mirrikh.com/wp-content/uploads/2026/02/Mayur-Ananta-2-hero-2.jpg',
    highlights: [
      'Fully RERA Approved',
      'Prime main road facing units',
      'High rental yield potential',
      'Immediate possession',
    ],
    accent: '#f472b6',
    desc: 'A flagship commercial property offering RERA-approved, ready-to-move shops. Located on the main arterial roads of Dholera Smart City, these shops guarantee high footfall and excellent rental yields for early investors.',
  },
];

export const faqs = [
  {
    q: 'Why is Dholera Smart City a good investment in 2026?',
    a: "Dholera SIR is India's first greenfield smart city. With the ₹91,000 crore Tata semiconductor fab, the international airport nearing completion and the Ahmedabad–Dholera Expressway, land prices are still at an early-growth stage, giving strong long-term appreciation potential.",
  },
  {
    q: 'Are the plots legal and title clear?',
    a: 'Yes. Every project is NA (Non-Agricultural), NOC-approved, title clear and plan passed. Sales are completed only through a registered sale deed in your name.',
  },
  {
    q: 'What is the minimum investment to buy a plot in Dholera?',
    a: 'A typical plot starts around ₹10,750 per sq yd depending on the project and location. Flexible payment plans are available.',
  },
  {
    q: 'Is Dholera investment safe for NRIs?',
    a: 'Yes. NRIs can legally purchase non-agricultural residential and commercial plots in India. Our NA-approved, registered-deed process is fully NRI friendly and we assist with documentation end to end.',
  },
];