export const site = {
  name: 'Mayur Dholera',
  tagline: 'Premium Plots near Dholera Smart City',
  phone: '9899974590',
  phoneAlt: '7042367340',
  phoneDisplay: '+91 98999 74590',
  email: 'info@mayurdholera.com',
  address: 'Site: Near Dholera International Airport, Dholera SIR, Gujarat',
  whatsappMessage:
    'Hi! I am interested in Mayur Dholera projects. Please share current prices and plot availability.',
};

export const stats = [
  { value: '₹91,000 Cr', label: 'Tata Semiconductor Fab in Dholera' },
  { value: '15+', label: 'Projects Delivered in Dholera' },
  { value: '920 km²', label: "India's Largest Planned Smart City" },
  { value: '2026', label: 'International Airport Operational' },
];

export const whyDholera = [
  {
    icon: 'Landmark',
    title: 'Government-Backed SIR',
    text: "Dholera is a Gujarat Government notified Special Investment Region under the Delhi–Mumbai Industrial Corridor (DMIC) — India's first and largest greenfield smart city, with plug-and-play trunk infrastructure already built.",
  },
  {
    icon: 'Cpu',
    title: '₹91,000 Cr Semiconductor Hub',
    text: "Tata Electronics' mega semiconductor fabrication plant — producing India's first homegrown chips — anchors Dholera's industrial ecosystem, drawing suppliers, engineers and housing demand.",
  },
  {
    icon: 'Plane',
    title: 'International Airport',
    text: 'Dholera International Airport (Navagam) is in advanced construction, designed for both cargo and passenger operations — a direct catalyst for land appreciation around the SIR.',
  },
  {
    icon: 'Route',
    title: 'Expressway Connectivity',
    text: 'The 109 km, 4-lane Ahmedabad–Dholera Expressway cuts travel time to under an hour, with high-speed rail and metro links planned along the corridor.',
  },
  {
    icon: 'TrendingUp',
    title: 'Early-Growth Pricing',
    text: 'Plot rates in Dholera are still in the early phase — roughly ₹6,000–₹10,000 per sq yd against mature Ahmedabad markets, giving investors a rare ground-floor entry.',
  },
  {
    icon: 'ShieldCheck',
    title: 'Clear-Title, Legal Plots',
    text: 'Every plot is NA (Non-Agricultural), NOC-approved, title clear and plan passed — sold with registered sale deed for a fully transparent purchase.',
  },
];

export const projects = [
  {
    name: 'Mayur NOVA',
    slug: 'mayur-nova',
    type: 'Residential Plots',
    category: 'Ongoing',
    location: 'Ratanpur, Dholera Smart City',
    price: 'On Request',
    priceUnit: 'New Launch',
    size: '90 plots · 132–655 sq yd',
    status: 'New Launch',
    image: 'https://mirrikh.com/wp-content/uploads/2026/07/Mayur-NOVA-cover-banner-2.jpg',
    logo: 'https://mirrikh.com/wp-content/uploads/2026/07/Mayur-NOVA-logo.png', // Fallback if missing
    highlights: [
      'NA, NOC, Title Clear & Unit Plan Pass',
      'Gated Community with Club House',
      '10 km from Dholera International Airport',
      '9 km from Ahmedabad–Dholera Expressway',
    ],
    accent: '#f26522',
    desc: 'Mayur NOVA is a premium residential plotting project situated in Ratanpur. Featuring 90 exclusive plots ranging from 132 to 655 sq yd, the project comes with complete NA, NOC, and title clearance. Enjoy world-class amenities including a modern clubhouse within a secure gated community.',
  },
  {
    name: 'Mayur Aerocity II',
    slug: 'mayur-aerocity-ii',
    type: 'Residential Plots',
    category: 'Ongoing',
    location: 'Near Dholera International Airport',
    price: 'On Request',
    priceUnit: 'Pre-Launch Pricing',
    size: 'Multiple plot sizes',
    status: 'Pre-Launch',
    image: 'https://mirrikh.com/wp-content/uploads/2026/07/Mayur-Aerocity-ll-cover-bg3.jpg',
    logo: 'https://mirrikh.com/wp-content/uploads/2026/07/Mayur-Aerocity-ll-logo.png', // Fallback
    highlights: [
      'Closest project to Dholera Airport',
      'High appreciation potential',
      'NA · NOC · Title Clear',
      'Registered sale deed guaranteed',
    ],
    accent: '#3b82f6',
    desc: 'Strategically located near the upcoming Dholera International Airport, Mayur Aerocity II is designed for investors seeking high appreciation. The project offers premium plotting options with guaranteed registered sale deeds and unmatched proximity to major transport hubs.',
  },
  {
    name: 'Mayur Park III',
    slug: 'mayur-park-3',
    type: 'Residential Plots',
    category: 'Ongoing',
    location: 'Valinda, Dholera Smart City',
    price: 'On Request',
    priceUnit: 'Ongoing',
    size: 'Multiple plot sizes',
    status: 'Ongoing',
    image: 'https://mirrikh.com/wp-content/uploads/2026/06/Mayur-Park-3-by-Mirrikh-Group-1pdf.jpg',
    logo: 'https://mirrikh.com/wp-content/uploads/2026/06/Mayur-Park-3-by-Mirrikh-Group-logo2.jpg',
    highlights: [
      'Near Dholera SIR Boundary',
      'Well-planned internal roads',
      'Green open areas',
      'NA · NOC · Title Clear',
    ],
    accent: '#e8c774',
    desc: 'Mayur Park III is a premium residential project located in Valinda, Dholera Smart City, strategically positioned near the Dholera SIR Boundary (Industrial Zone). It offers thoughtfully planned residential spaces with robust infrastructure.',
  },
  {
    name: 'Mayur Forest Villa',
    slug: 'mayur-forest-villa',
    type: 'Villa Plots',
    category: 'Ongoing',
    location: 'Dholera Smart City',
    price: 'On Request',
    priceUnit: 'Ongoing',
    size: 'Multiple plot sizes',
    status: 'Ongoing',
    image: 'https://mirrikh.com/wp-content/uploads/2026/05/Mayur-Forest-Villa-Dholera-1.jpg',
    logo: 'https://mirrikh.com/wp-content/uploads/2026/05/Mayur-Forest-Villa-Dholera-logo1.jpg',
    highlights: [
      'Forest-themed residential community',
      'Lush greenery & landscaped spaces',
      'Gated community with premium amenities',
      'NA · NOC · Title Clear',
    ],
    accent: '#22c55e',
    desc: 'Mayur Forest Villa is a thoughtfully planned residential project offering premium villa plots amidst lush greenery and smart urban infrastructure, designed for sustainable and luxurious living.',
  },
  {
    name: 'Mayur Greenz Courtyard',
    slug: 'mayur-greenz-courtyard',
    type: 'Luxury Villas',
    category: 'Ongoing',
    location: 'Dholera Smart City',
    price: 'On Request',
    priceUnit: 'Pre-Launch',
    size: 'Large-format plots',
    status: 'Ongoing',
    image: 'https://mirrikh.com/wp-content/uploads/2026/04/Mayur-Greenz-Courtyard-Single-Images_Optimizer-1.jpg',
    logo: 'https://mirrikh.com/wp-content/uploads/2026/04/Mayur-Greenz-Courtyard-logo.svg',
    highlights: [
      'Roman architecture inspired',
      'Premium lifestyle amenities',
      'Gated community',
      'Excellent connectivity',
    ],
    accent: '#f59e0b',
    desc: 'Mayur Greenz Courtyard is a distinguished enclave of luxury villas inspired by the grace of Roman architecture, thoughtfully re-imagined for modern living with expansive open spaces and premium lifestyle amenities.',
  },
  {
    name: 'Mayur Ananta II',
    slug: 'mayur-ananta-ii',
    type: 'Residential Plots',
    category: 'Ongoing',
    location: 'Dholera Smart City',
    price: 'On Request',
    priceUnit: 'Ongoing',
    size: 'Multiple configurations',
    status: 'Ongoing',
    image: 'https://mirrikh.com/wp-content/uploads/2026/07/Mayur-Ananta-II-by-Mirrikh-Infratech-1.jpg',
    logo: 'https://mirrikh.com/wp-content/uploads/2026/02/Mayur-Ananta-logo2.png',
    highlights: [
      'Largest premium residential land project',
      'High appreciation potential',
      'Excellent connectivity',
      'NA · NOC · Title Clear',
    ],
    accent: '#8b5cf6',
    desc: 'After the remarkable success of Mayur Ananta, we present Mayur Ananta II. The largest premium residential land project in its segment in the Dholera Smart City region offering unmatched appreciation potential.',
  },
  {
    name: 'Mayur Industrial Landmark',
    slug: 'mayur-industrial-landmark',
    type: 'Industrial Plots',
    category: 'Commercial',
    location: 'Dholera Smart City',
    price: 'On Request',
    priceUnit: 'Ongoing',
    size: 'Multiple configurations',
    status: 'Ongoing',
    image: 'https://mirrikh.com/wp-content/uploads/2026/06/MIL-by-Mirrikh-Group-1.jpg',
    logo: 'https://mirrikh.com/wp-content/uploads/2026/01/Mayur-Industrial-Landmark-logo.png',
    highlights: [
      'Strategic industrial opportunity',
      'Near modern manufacturing hubs',
      'Heavy-vehicle friendly access',
      'NA · NOC · Title Clear',
    ],
    accent: '#64748b',
    desc: 'Located in Dholera Smart City, India\'s emerging modern manufacturing hub, this industrial plot project offers a strategic opportunity to invest in world-class infrastructure tailored for businesses.',
  }
];

export const faqs = [
  {
    q: 'Why is Dholera Smart City a good investment in 2026?',
    a: "Dholera SIR is India's first greenfield smart city. With the ₹91,000 crore Tata semiconductor fab, the international airport nearing completion and the Ahmedabad–Dholera Expressway, land prices are still at an early-growth stage, giving strong long-term appreciation potential.",
  },
  {
    q: 'Are the plots legal and title clear?',
    a: 'Yes. Every project is NA (Non-Agricultural), NOC-approved, title clear and plan passed. Sales are completed only through a registered sale deed in your name.',
  },
  {
    q: 'What is the minimum investment to buy a plot in Dholera?',
    a: 'A typical plot starts around ₹10,750 per sq yd depending on the project and location. Flexible payment plans are available.',
  },
  {
    q: 'Is Dholera investment safe for NRIs?',
    a: 'Yes. NRIs can legally purchase non-agricultural residential and commercial plots in India. Our NA-approved, registered-deed process is fully NRI friendly and we assist with documentation end to end.',
  },
];